### ISSUE TITLE
[Suggestion] Curios/Trinkets support

### ISSUE THREAD

**Issue by MechanosG** [Geometrically/Gravestones#21]
A few mods use the extra inventory slots those provide.  But currently when you die, those items get thrown on the ground instead.  Support for those mods would be awesome, especially considering Better Graves doesn't have proper support either.

**Comment by JuergenSchT** [comment]
Gravestones does support Trinkets; it might not have seemed like it because the API was configured incorrectly on Gravestones' end in previous versions [it got fixed in 1.8].
As for Curios mods, I reported that issue months ago (https://github.com/Geometrically/Gravestones/issues/14). I assume it would require the implementation of the API on Gravestones, like Trinkets.

**Comment by Crispot123** [comment]
it's a bit annoying to still not have mod support for trinkets

**Comment by JordanPlayz158** [comment]
https://github.com/PTOM76/Gravestones/pull/3 PTOM76 seems to be the new maintainer of Gravestones on modrinth and I have made a PR, it was a fun little thing to figure out

Edit: Not perfect/not working with all trinkets
